import type { Metadata } from "next";
import { pretendard } from "@/public/fonts/font";
import "./globals.css";
import CustomLayout from "@/components/layout/custom-layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable} antialiased`}>
      <body>
        <CustomLayout>{children}</CustomLayout>
      </body>
    </html>
  );
}
